name: Rishi Kothari, Developer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

internships: true

plugins:
  - jekyll-random

collections:
  projects:
    output: true
    permalink: /projects/:name
